### ISSUE TITLE
Changing project name leads to failing tests

### ISSUE THREAD

**Issue by madagiurgiu25** [seqan/app-template#57]
Dear team,

I try to run the tests for the `app-template` but the `fastq_to_fasta_options_test` fails if I changed the PROJECT_NAME. 
The issue is due to statically defined project_name in each test. 

I tried to fix this by adding the cmake PROJECT_NAME variable to the C++ code.
Under the `app-template/test/` I created a file called `config.h.in`:

```
#ifndef CONFIG_H_IN
#define CONFIG_H_IN
 
#define PROJECT_NAME_CONFIG_H "@PROJECT_NAME@"

#endif // CONFIG_H_IN% 
```

And modified the `app-template/test/CMakeList.txt`:

```
# Specify the configuration file from which the header file will be generated
configure_file(config.h.in ${CMAKE_BINARY_DIR}/generated/config.h)
include_directories( ${CMAKE_BINARY_DIR}/generated/ )
```

Afterwards I changed in the `app-template/test/cli/fastq_to_fasta_options_test`:

```
#include "cli_test.hpp"

#include "config.h" // #define PROJECT_NAME_CONFIG_H "seqan3_test"


// To prevent issues when running multiple CLI tests in parallel, give each CLI test unique names:
struct fastq_to_fasta : public cli_test {};

TEST_F(fastq_to_fasta, no_options)
{
    cli_test_result result = execute_app(PROJECT_NAME_CONFIG_H); // here was originally "app-template"
    std::string expected
    {

....
```

Hope it helps.

Best,
Madalina

**Comment by eseiler** [comment]
Hey there,

the existing tests in `api` and `cli` are just examples and might be modified (or just removed) as you see fit.

In this specific case, I would just change the app name in 

https://github.com/seqan/app-template/blob/95d1a2708c2bec0ebca03d9b01bc15b7d570c362/test/cli/fastq_to_fasta_options_test.cpp#L20

(and other occurrences) to whatever you want to name your app.

An alternative would be to add [definitions](https://cmake.org/cmake/help/latest/command/add_compile_definitions.html#command:add_compile_definitions), but I feel like it is quite "overkill" because your app name should remain static.

**Comment by madagiurgiu25** [comment]
Hi,

yes, this is what I initially did, I replaced the app name in the tests. Its just if you go through the app-template README.md  then `make test` will initialy fail. 

I was not sure to which extend you would like to make the app-template agnostic. This is why I wrote you how I fix this (for me a learning exercise).
If the tests are just exemplary then I see your point. I will then close the ticket.
